(ns q07
  (:require [clojure.string :as str]
            [util :as util]))

(defn make-rule
  "Make a map out of a rule"
  [s]
  (let [[k v] (str/split s #"\s>\s")]
    {k (str/split v #",")}))

(defn produces?
  "Check that the production a -> b is a valid rule."
  [rules a b]
  (and (contains? rules a)
       (util/in? (get rules a) b)))

(defn read-data
  [f]
  (let [[a b] (->> f
                   slurp
                   str/split-lines
                   (split-with (comp not str/blank?)))
        words (str/split (first a) #",")
        rules (reduce 
                #(into %1 (make-rule %2)) 
                {} 
                (rest b))]
    [words rules]))

(defn valid-word?
  "Check if the letters can be generated by the rules."
  [rules word]
  (let [pairs (partition 2 1 (str/split word #""))]
    (every? #(apply produces? rules %) pairs)))

(defn part1
  "Solution for part 1"
  [fname]
  (let [[words rules] (read-data fname)]
    (filter #(valid-word? rules %) words)))

(defn part2
  "Solution for part 2"
  [fname])

(comment
  (def testf1 "data/q07_p1_test.txt")
  (def inputf1 "data/q07_p1.txt")
  (def testf2 "data/q07_p2_test.txt")
  (def inputf2 "data/q07_p2.txt")

  (part1 testf1)
  (part1 inputf1)

  (part2 testf2)
  (part2 inputf2))
;; The End
