(ns q09
  (:require [clojure.string :as str]
            [clojure.math.combinatorics :as combo]
            [util :as util]))

(defn read-data
  [f]
  (->> f
       slurp
       str/split-lines
       (map #(str/split % #":"))
       (map #(update % 0 Integer/parseInt))))

(defn count-matches
  "Count the number of element-wise matches between a and b"
  [a b]
  (util/count-if true? (map = (second a) (second b))))

;;-------- Start generated by Claude
(defn- diff-mask
  "Bit t set iff a and b differ at position t."
  ^longs [^String a ^String b]
  (let [L (.length a)
        m (long-array (quot (+ L 63) 64))]
    (dotimes [t L]
      (when-not (= (.charAt a t) (.charAt b t))
        (aset m (quot t 64)
              (bit-or (aget m (quot t 64)) (bit-shift-left 1 t)))))
    m))

(defn- overlap ^long [^longs a ^longs b]
  (areduce a w acc 0 (+ acc (Long/bitCount (bit-and (aget a w) (aget b w))))))

(defn- card ^long [^longs a]
  (areduce a w acc 0 (+ acc (Long/bitCount (aget a w)))))

(defn- bit-at? [^longs m ^long t]
  (bit-test (aget m (quot t 64)) (rem t 64)))

(defn- set-bits [^longs m]
  (for [w (range (alength m)), b (range 64)
        :when (bit-test (aget m w) b)]
    (+ (* 64 w) b)))

(defn- C [n k]
  (if (or (neg? k) (> k n)) 0N
      (reduce (fn [acc i] (/ (*' acc (- n i)) (inc i))) 1N (range k))))

(defn- runs-p [k b]
  (if (< k 2) 1.0
      (double (/ (reduce +' 0N (map #(C (dec k) %) (range (inc b))))
                 (reduce *' 1N (repeat (dec k) 2N))))))

(defn find-recombinants
  "strings: aligned, equal length. Returns triples ranked by significance.
  :max-uncovered  tolerate this many positions matching neither parent
  :min-informative  minimum |{i : p1[i] != p2[i]}|
  :min-contribution  minimum informative sites from each parent"
  [strings & {:keys [max-uncovered min-informative min-contribution]
              :or   {max-uncovered 0 min-informative 4 min-contribution 2}}]
  (let [ss (vec (distinct strings))
        n  (count ss)
        DM (mapv (fn [i] (mapv #(diff-mask (ss i) (ss %)) (range n))) (range n))
        d  (fn [i j] (get-in DM [i j]))]
    (->>
      (for [c  (range n)
            p1 (range n)      :when (and (not= p1 c) (pos? (card (d p1 c))))
            p2 (range (inc p1) n)
            :when (and (not= p2 c) (pos? (card (d p2 c))))
            :let  [u (overlap (d p1 c) (d p2 c))]
            :when (<= u max-uncovered)
            :let  [inf (set-bits (d p1 p2))
                   k   (count inf)]
            :when (>= k min-informative)
            :let  [src (map #(if (bit-at? (d p1 c) %) :p2 :p1) inf)
                   n1  (count (filter #{:p1} src))
                   bp  (count (filter true? (map not= src (rest src))))]
            :when (and (>= n1 min-contribution)
                       (>= (- k n1) min-contribution))]
        {:child (inc c) 
         :p1 (inc p1) 
         :p2 (inc p2)
         :score [(util/count-if true? (map = (nth strings c) (nth strings p1))) 
                 (util/count-if true? (map = (nth strings c) (nth strings p2)))]})
      (sort-by :p))))
;;-------- End generated by Claude

(defn part1
  "Solution for part 1"
  [fname]
  (let [dna (read-data fname)]
    (* (count-matches (nth dna 0) (nth dna 2))
       (count-matches (nth dna 1) (nth dna 2)))))

(defn part2
  "Solution for part 2"
  [fname]
  (let [dna (read-data fname)]
    (->> dna
         (map second)
         find-recombinants
         (map :score)
         (map (partial apply *))
         (apply +))))

(comment
  (def testf1 "data/q09_p1_test.txt")
  (def inputf1 "data/q09_p1.txt")
  (def testf2 "data/q09_p2_test.txt")
  (def inputf2 "data/q09_p2.txt")

  (part1 testf1)
  (part1 inputf1)

  (part2 testf2)
  (part2 inputf2))
;; The End
